import { useState } from 'react';
import { RetroBadge, RetroButton, RetroCard, RetroInput, RetroSelect, RetroTable, RetroTabs, formatMoney2 } from '@retroburger/ui';
import { post, put } from '../app/api';
import { useAct, useGet } from '../app/hooks';
import { useSession } from '../app/auth';
import { Async, FormModal, INV_STATUS, NeedBranch, Row, StatusBadge, fmtDate, num } from './common';

type Tab = 'stock' | 'kardex' | 'counts' | 'transfers' | 'expiring' | 'integrity';
export default function Inventory() { return <NeedBranch>{(b) => <Inner branchId={b} />}</NeedBranch>; }

function Inner({ branchId }: { branchId: string }) {
  const { can } = useSession(); const [tab, setTab] = useState<Tab>('stock'); const [status, setStatus] = useState(''); const [all, setAll] = useState(false);
  const stock = useGet<any[]>(['inventory', branchId, all, status], '/inventory', { branchId: all ? undefined : branchId, status: status || undefined });
  const [mv, setMv] = useState<any | null>(null); const [lv, setLv] = useState<any | null>(null); const [kIng, setKIng] = useState('');
  const kardex = useGet<any[]>(['inventory', 'kardex', branchId, kIng], '/inventory/kardex', { branchId, ingredientId: kIng || undefined, limit: 100 }, { enabled: tab === 'kardex' });
  const transfers = useGet<any[]>(['inventory', 'transfers', branchId], '/transfers', { branchId }, { enabled: tab === 'transfers' });
  const recon = useGet<any>(['inventory', 'recon', branchId], '/inventory/reconciliation', { branchId }, { enabled: tab === 'integrity' });
  const exp = useGet<any[]>(['inventory', 'exp', branchId], '/inventory/expiring', { branchId, days: 14 }, { enabled: tab === 'expiring' });
  const branches = useGet<any[]>(['branches'], '/branches'); const ingredients = useGet<any[]>(['ingredients'], '/ingredients');
  const [tf, setTf] = useState<any | null>(null); const [count, setCount] = useState<any | null>(null);
  const inv = [['inventory'], ['dashboard']];
  const move = useAct(() => post('/inventory/movements', { branchId, ingredientId: mv.ingredientId, type: mv.type, qty: mv.type === 'WASTE' || (mv.type === 'ADJUSTMENT' && mv.neg) ? -Math.abs(num(mv.qty)) : Math.abs(num(mv.qty)), unitCost: mv.unitCost ? num(mv.unitCost) : undefined, reason: mv.reason || undefined, lotCode: mv.lotCode || undefined, expiresOn: mv.expiresOn || undefined }), { invalidate: inv, ok: 'Movimiento registrado', onSuccess: () => setMv(null) });
  const levels = useAct(() => put('/inventory/levels', { branchId, ingredientId: lv.ingredientId, minQty: num(lv.minQty), maxQty: num(lv.maxQty) }), { invalidate: inv, ok: 'Niveles guardados', onSuccess: () => setLv(null) });
  const createTf = useAct(() => post('/transfers', { fromBranchId: tf.from, toBranchId: branchId, items: [{ ingredientId: tf.ingredientId, qty: num(tf.qty) }] }), { invalidate: inv, ok: 'Transferencia solicitada', onSuccess: () => setTf(null) });
  const tfAct = useAct((v: { id: string; a: string }) => post(`/transfers/${v.id}/${v.a}`), { invalidate: inv, ok: 'Transferencia actualizada' });
  const startCount = useAct(() => post('/inventory/counts', { branchId }), { onSuccess: (c) => setCount({ ...c, edits: {} }) });
  const submitCount = useAct(async () => { await (await import('../app/api')).put(`/inventory/counts/${count.id}/items`, { items: Object.entries(count.edits).map(([ingredientId, v]) => ({ ingredientId, countedQty: num(String(v)) })) }); return post(`/inventory/counts/${count.id}/apply`); }, { invalidate: inv, ok: 'Inventario físico aplicado', onSuccess: () => setCount(null) });

  const rows = stock.data ?? [];
  const canWrite = can('inventory.movement.write', branchId);
  return (
    <>
      <RetroTabs value={tab} onChange={setTab} tabs={[{ key: 'stock', label: '📦 Existencias' }, { key: 'kardex', label: '📒 Kardex' }, { key: 'counts', label: '🧮 Inventario físico' }, { key: 'transfers', label: '🔁 Transferencias' }, { key: 'expiring', label: '⏳ Caducidades' }, { key: 'integrity', label: '🧮 Integridad' }]} />
      {tab === 'stock' && <>
        <div className="rb-row rb-wrap"><RetroSelect aria-label="Estado" value={status} onChange={(e) => setStatus(e.target.value)} options={[{ value: '', label: 'Todos los estados' }, { value: 'AVAILABLE', label: '🟢 Normal' }, { value: 'LOW', label: '🟡 Bajo' }, { value: 'CRITICAL', label: '🔴 Crítico' }, { value: 'OUT_OF_STOCK', label: '⚫ Agotado' }]} />
          {can('reports.corporate.read') && <label className="rb-check"><input type="checkbox" checked={all} onChange={(e) => setAll(e.target.checked)} />Ver todas las sucursales</label>}
          {canWrite && <span className="rb-end rb-row"><RetroButton variant="neon" onClick={() => setMv({ type: 'PURCHASE_IN', qty: '', ingredientId: '' })}>⬇️ Entrada</RetroButton><RetroButton variant="mustard" onClick={() => setMv({ type: 'WASTE', qty: '', ingredientId: '' })}>🗑 Merma</RetroButton><RetroButton variant="white" onClick={() => setMv({ type: 'ADJUSTMENT', qty: '', ingredientId: '', neg: false })}>± Ajuste</RetroButton></span>}</div>
        <Async q={stock}><RetroTable rows={rows} rowKey={(r) => `${r.branchId}:${r.ingredientId}`} onRowClick={canWrite && !all ? (r) => setLv({ ingredientId: r.ingredientId, name: r.name, minQty: r.minQty, maxQty: r.maxQty }) : undefined} columns={[
          ...(all ? [{ key: 'b', header: 'Sucursal', render: (r: any) => r.branchName }] : []), { key: 'n', header: 'Insumo', render: (r: any) => <><strong>{r.name}</strong> {r.needsReview && <RetroBadge tone="warn">Revisar</RetroBadge>}</> },
          { key: 'q', header: 'Existencia', numeric: true, render: (r: any) => `${Math.round(r.qty * 100) / 100} ${r.unit}` }, { key: 'min', header: 'Mín.', numeric: true, render: (r: any) => r.minQty }, { key: 'max', header: 'Máx.', numeric: true, render: (r: any) => r.maxQty },
          ...(can('inventory.cost.read') ? [{ key: 'c', header: 'Costo prom.', numeric: true, render: (r: any) => (r.avgCost == null ? '—' : formatMoney2(r.avgCost)) }] : []), { key: 's', header: 'Estado', render: (r: any) => <StatusBadge s={r.status} map={INV_STATUS} /> }]} /></Async>
        {canWrite && <span className="rb-hint">Toca un insumo para editar sus mínimos y máximos.</span>}
      </>}
      {tab === 'kardex' && <><RetroSelect aria-label="Insumo" value={kIng} onChange={(e) => setKIng(e.target.value)} options={[{ value: '', label: 'Todos los insumos' }, ...(ingredients.data ?? []).map((i) => ({ value: i.id, label: i.name }))]} />
        <Async q={kardex}><RetroTable rows={kardex.data ?? []} columns={[{ key: 'at', header: 'Fecha', render: (r: any) => fmtDate(r.at) }, { key: 'i', header: 'Insumo', render: (r: any) => r.ingredient }, { key: 't', header: 'Tipo', render: (r: any) => <RetroBadge tone={r.qty > 0 ? 'ok' : 'warn'}>{r.type}</RetroBadge> }, { key: 'q', header: 'Cantidad', numeric: true, render: (r: any) => `${r.qty > 0 ? '+' : ''}${r.qty} ${r.unit}` }, { key: 'b', header: 'Saldo', numeric: true, render: (r: any) => r.balanceAfter }, { key: 'u', header: 'Usuario', render: (r: any) => r.user ?? '—' }, { key: 'r', header: 'Motivo', render: (r: any) => r.reason ?? '' }]} /></Async></>}
      {tab === 'counts' && <RetroCard title="🧮 Inventario físico" tone="plain"><div className="rb-col"><p style={{ margin: 0 }}>Conteo <strong>ciego</strong>: captura lo que hay físicamente; al aplicarlo, el sistema genera los ajustes (COUNT_ADJ) con trazabilidad. Requiere permiso de aprobación.</p><RetroButton variant="neon" loading={startCount.isPending} onClick={() => startCount.mutate()}>Iniciar conteo</RetroButton></div></RetroCard>}
      {tab === 'transfers' && <><div className="rb-row"><RetroButton variant="neon" onClick={() => setTf({ from: '', ingredientId: '', qty: '' })}>+ Solicitar transferencia a esta sucursal</RetroButton></div>
        <Async q={transfers}><RetroTable rows={transfers.data ?? []} columns={[{ key: 'n', header: '#', render: (r: any) => r.number }, { key: 'f', header: 'Origen', render: (r: any) => branches.data?.find((b) => b.id === r.fromBranchId)?.name ?? '—' }, { key: 't', header: 'Destino', render: (r: any) => branches.data?.find((b) => b.id === r.toBranchId)?.name ?? '—' }, { key: 's', header: 'Estado', render: (r: any) => <RetroBadge tone={r.status === 'RECEIVED' ? 'ok' : r.status === 'CANCELLED' ? 'danger' : 'info'}>{r.status}</RetroBadge> }, { key: 'at', header: 'Fecha', render: (r: any) => fmtDate(r.createdAt) },
          { key: 'a', header: 'Acciones', render: (r: any) => <span className="rb-row rb-wrap">{r.status === 'REQUESTED' && can('inventory.transfer.approve') && <RetroButton size="sm" variant="neon" onClick={() => tfAct.mutate({ id: r.id, a: 'approve' })}>Aprobar</RetroButton>}{r.status === 'APPROVED' && <RetroButton size="sm" variant="mustard" onClick={() => tfAct.mutate({ id: r.id, a: 'dispatch' })}>Despachar</RetroButton>}{r.status === 'IN_TRANSIT' && <RetroButton size="sm" variant="neon" onClick={() => tfAct.mutate({ id: r.id, a: 'receive' })}>Recibir</RetroButton>}{['REQUESTED', 'APPROVED', 'IN_TRANSIT'].includes(r.status) && <RetroButton size="sm" variant="ghost" onClick={() => tfAct.mutate({ id: r.id, a: 'cancel' })}>Cancelar</RetroButton>}</span> }]} /></Async></>}
      {tab === 'integrity' && <Async q={recon}><RetroCard title="🧮 Conciliación kardex ↔ saldo ↔ lotes" tone={recon.data?.ok ? 'plain' : 'red'} actions={<RetroButton size="sm" variant="white" onClick={() => void recon.refetch()}>↻ Revisar ahora</RetroButton>}><p style={{ marginTop: 0 }}>{recon.data?.findings.length ? (recon.data.ok ? 'Hay advertencias por revisar.' : '⚠️ Hay diferencias entre el saldo y el kardex. Avisa a administración antes de seguir operando ese insumo.') : '✅ Todo cuadra: el saldo de cada insumo coincide con su kardex. Se revisa automáticamente cada noche.'}</p>{recon.data?.findings.length > 0 && <RetroTable rows={recon.data.findings} rowKey={(r: any) => r.kind + r.ingredientId} columns={[{ key: 'i', header: 'Insumo', render: (r: any) => r.ingredient }, { key: 'k', header: 'Hallazgo', render: (r: any) => <RetroBadge tone={r.severity === 'CRITICAL' ? 'danger' : 'warn'}>{r.kind}</RetroBadge> }, { key: 'd', header: 'Detalle', render: (r: any) => r.detail }]} />}</RetroCard></Async>}
      {tab === 'expiring' && <Async q={exp}><RetroTable rows={exp.data ?? []} columns={[{ key: 'i', header: 'Insumo', render: (r: any) => r.ingredient }, { key: 'l', header: 'Lote', render: (r: any) => r.lotCode ?? '—' }, { key: 'e', header: 'Caduca', render: (r: any) => String(r.expiresOn).slice(0, 10) }, { key: 'd', header: 'Días', numeric: true, render: (r: any) => <RetroBadge tone={r.daysLeft <= 2 ? 'danger' : 'warn'}>{r.daysLeft}</RetroBadge> }, { key: 'q', header: 'Cantidad', numeric: true, render: (r: any) => `${r.qty} ${r.unit}` }]} empty="Sin caducidades en 14 días 🎉" /></Async>}

      <FormModal open={!!mv} onClose={() => setMv(null)} title={mv?.type === 'PURCHASE_IN' ? '⬇️ Entrada de mercancía' : mv?.type === 'WASTE' ? '🗑 Merma' : '± Ajuste'} busy={move.isPending} disabled={!mv?.ingredientId || !num(mv?.qty ?? '0')} onSubmit={() => move.mutate()}>
        {mv && <><RetroSelect label="Insumo" value={mv.ingredientId} onChange={(e) => setMv({ ...mv, ingredientId: e.target.value })} options={[{ value: '', label: 'Selecciona…' }, ...(ingredients.data ?? []).map((i) => ({ value: i.id, label: `${i.name} (${i.unit})` }))]} />
          <Row><RetroInput label="Cantidad" inputMode="decimal" value={mv.qty} onChange={(e) => setMv({ ...mv, qty: e.target.value.replace(/[^\d.]/g, '') })} />{mv.type === 'ADJUSTMENT' && <RetroSelect label="Sentido" value={mv.neg ? 'neg' : 'pos'} onChange={(e) => setMv({ ...mv, neg: e.target.value === 'neg' })} options={[{ value: 'pos', label: 'Aumenta (+)' }, { value: 'neg', label: 'Disminuye (−)' }]} />}{mv.type === 'PURCHASE_IN' && <RetroInput label="Costo unitario" inputMode="decimal" value={mv.unitCost ?? ''} onChange={(e) => setMv({ ...mv, unitCost: e.target.value })} />}</Row>
          {mv.type === 'PURCHASE_IN' && <Row><RetroInput label="Lote" value={mv.lotCode ?? ''} onChange={(e) => setMv({ ...mv, lotCode: e.target.value })} /><RetroInput label="Caducidad" type="date" value={mv.expiresOn ?? ''} onChange={(e) => setMv({ ...mv, expiresOn: e.target.value })} /></Row>}
          {mv.type !== 'PURCHASE_IN' && <RetroInput label="Motivo (obligatorio)" value={mv.reason ?? ''} onChange={(e) => setMv({ ...mv, reason: e.target.value })} />}</>}
      </FormModal>
      <FormModal open={!!lv} onClose={() => setLv(null)} title={`Niveles · ${lv?.name}`} busy={levels.isPending} onSubmit={() => levels.mutate()} size="sm">{lv && <Row><RetroInput label="Mínimo" inputMode="decimal" value={lv.minQty} onChange={(e) => setLv({ ...lv, minQty: e.target.value })} /><RetroInput label="Máximo" inputMode="decimal" value={lv.maxQty} onChange={(e) => setLv({ ...lv, maxQty: e.target.value })} /></Row>}</FormModal>
      <FormModal open={!!tf} onClose={() => setTf(null)} title="Solicitar transferencia" busy={createTf.isPending} disabled={!tf?.from || !tf?.ingredientId || !num(tf?.qty ?? '0')} onSubmit={() => createTf.mutate()} size="sm">{tf && <><RetroSelect label="Sucursal origen" value={tf.from} onChange={(e) => setTf({ ...tf, from: e.target.value })} options={[{ value: '', label: 'Selecciona…' }, ...(branches.data ?? []).filter((b) => b.id !== branchId).map((b) => ({ value: b.id, label: b.name }))]} /><RetroSelect label="Insumo" value={tf.ingredientId} onChange={(e) => setTf({ ...tf, ingredientId: e.target.value })} options={[{ value: '', label: 'Selecciona…' }, ...(ingredients.data ?? []).map((i) => ({ value: i.id, label: `${i.name} (${i.unit})` }))]} /><RetroInput label="Cantidad" inputMode="decimal" value={tf.qty} onChange={(e) => setTf({ ...tf, qty: e.target.value })} /></>}</FormModal>
      <FormModal open={!!count} onClose={() => setCount(null)} title="🧮 Conteo físico" size="lg" busy={submitCount.isPending} submitLabel="Aplicar diferencias" onSubmit={() => submitCount.mutate()}>
        {count && <div className="rb-table-wrap"><table className="rb-table"><thead><tr><th>Insumo</th><th>Unidad</th><th>Contado</th></tr></thead><tbody>{count.items.map((i: any) => <tr key={i.ingredientId}><td>{i.name}</td><td>{i.unit}</td><td><input aria-label={`Cantidad contada de ${i.name}`} className="rb-input" inputMode="decimal" style={{ maxWidth: 140 }} value={count.edits[i.ingredientId] ?? ''} onChange={(e) => setCount({ ...count, edits: { ...count.edits, [i.ingredientId]: e.target.value } })} /></td></tr>)}</tbody></table></div>}
      </FormModal>
    </>
  );
}
