import { useState } from 'react';
import { RetroBadge, RetroButton, RetroCheck, RetroInput, RetroSelect, RetroTable, RetroTabs, RetroTextarea, formatMoney2 } from '@retroburger/ui';
import { STATION_KEYS, UNITS } from '@retroburger/shared';
import { del, get, post, put } from '../app/api';
import { useAct, useGet } from '../app/hooks';
import { useSession } from '../app/auth';
import { Async, FormModal, Row, num } from './common';

type Tab = 'products' | 'categories' | 'modifiers' | 'ingredients';
export default function MenuAdmin() {
  const [tab, setTab] = useState<Tab>('products');
  return <><RetroTabs value={tab} onChange={setTab} tabs={[{ key: 'products', label: '🍔 Productos' }, { key: 'categories', label: '🗂️ Categorías' }, { key: 'modifiers', label: '➕ Modificadores' }, { key: 'ingredients', label: '🥩 Ingredientes' }]} />
    {tab === 'products' && <Products />}{tab === 'categories' && <Categories />}{tab === 'modifiers' && <Modifiers />}{tab === 'ingredients' && <Ingredients />}</>;
}

function Products() {
  const { can } = useSession(); const showCost = can('catalog.cost.read');
  const q = useGet<any[]>(['catalog', 'products'], '/products', { limit: 500 }); const cats = useGet<any[]>(['catalog', 'cats'], '/categories'); const taxes = useGet<any[]>(['catalog', 'taxes'], '/taxes');
  const groups = useGet<any[]>(['catalog', 'groups'], '/modifier-groups'); const ings = useGet<any[]>(['ingredients'], '/ingredients'); const allProducts = q.data ?? [];
  const [f, setF] = useState<any | null>(null); const [search, setSearch] = useState('');
  const payload = (x: any) => ({ categoryId: x.categoryId || null, kind: x.kind, sku: x.sku, barcode: x.barcode || null, name: x.name, description: x.description || null, imageUrl: x.imageUrl || null, price: num(String(x.price ?? 0)), taxId: x.taxId || null,
    isAvailable: x.isAvailable ?? true, isInventoriable: x.isInventoriable ?? true, prepTimeSec: Math.round(num(String(x.prepMin ?? (x.prepTimeSec ?? 300) / 60)) * 60), stationKey: x.stationKey || null, sortOrder: x.sortOrder ?? 0,
    variants: (x.variants ?? []).filter((v: any) => v.name).map((v: any) => ({ name: v.name, priceDelta: num(String(v.priceDelta ?? 0)), qtyFactor: num(String(v.qtyFactor ?? 1)) || 1 })), modifierGroupIds: x.modifierGroupIds ?? [],
    comboSlots: x.kind === 'COMBO' ? (x.comboSlots ?? []).map((s: any) => ({ name: s.name, defaultProductId: s.defaultProductId, options: (s.options ?? []).filter((o: any) => o.productId).map((o: any) => ({ productId: o.productId, priceDelta: num(String(o.priceDelta ?? 0)) })) })) : [],
    recipe: x.kind === 'COMBO' ? undefined : (x.recipe ?? []).filter((r: any) => r.ingredientId && num(String(r.qty)) > 0).map((r: any) => ({ ingredientId: r.ingredientId, qty: num(String(r.qty)), wastePct: num(String(r.wastePct ?? 0)) })) });
  const save = useAct(() => (f.id ? put(`/products/${f.id}`, payload(f)) : post('/products', payload(f))), { invalidate: [['catalog'], ['menu']], ok: 'Producto guardado 🍔', onSuccess: () => setF(null) });
  const remove = useAct((id: string) => del(`/products/${id}`), { invalidate: [['catalog'], ['menu']], ok: 'Producto eliminado', onSuccess: () => setF(null) });
  const edit = async (id: string) => { const p = await get(`/products/${id}`); setF({ ...p, prepMin: Math.round(p.prepTimeSec / 60) }); };
  const rows = allProducts.filter((p) => !search || p.name.toLowerCase().includes(search.toLowerCase()) || p.sku.toLowerCase().includes(search.toLowerCase()));
  const upd = (p: Partial<any>) => setF({ ...f, ...p });
  const simple = allProducts.filter((p) => p.kind === 'SIMPLE');

  return (
    <>
      <div className="rb-row rb-wrap"><RetroInput aria-label="Buscar" placeholder="🔎 Buscar producto o SKU" value={search} onChange={(e) => setSearch(e.target.value)} style={{ maxWidth: 320 }} />
        <span className="rb-end"><RetroButton variant="neon" onClick={() => setF({ kind: 'SIMPLE', price: '', isAvailable: true, isInventoriable: true, prepMin: 5, variants: [], modifierGroupIds: [], comboSlots: [], recipe: [], taxId: taxes.data?.find((t) => t.isDefault)?.id })}>+ Producto</RetroButton></span></div>
      <Async q={q}><RetroTable rows={rows} onRowClick={(r) => void edit(r.id)} columns={[{ key: 'sku', header: 'SKU' }, { key: 'name', header: 'Producto', render: (r: any) => <><strong>{r.name}</strong> {r.kind === 'COMBO' && <RetroBadge tone="orange">Combo</RetroBadge>}</> }, { key: 'cat', header: 'Categoría', render: (r: any) => cats.data?.find((c) => c.id === r.categoryId)?.name ?? '—' }, { key: 'st', header: 'Estación', render: (r: any) => r.stationKey ?? '—' },
        { key: 'price', header: 'Precio', numeric: true, render: (r: any) => formatMoney2(r.price) }, ...(showCost ? [{ key: 'cost', header: 'Costo', numeric: true, render: (r: any) => formatMoney2(r.cost) }, { key: 'm', header: 'Margen', numeric: true, render: (r: any) => <RetroBadge tone={r.margin >= 0.6 ? 'ok' : r.margin >= 0.4 ? 'warn' : 'danger'}>{Math.round(r.margin * 100)}%</RetroBadge> }] : []), { key: 'a', header: 'Disp.', render: (r: any) => (r.isAvailable ? '✅' : '⛔') }]} /></Async>
      <FormModal open={!!f} onClose={() => setF(null)} title={f?.id ? `Editar · ${f.name}` : 'Nuevo producto'} size="lg" busy={save.isPending} disabled={!f?.name || !f?.sku} onSubmit={() => save.mutate()}>
        {f && <>
          <Row><RetroInput label="Nombre" value={f.name ?? ''} onChange={(e) => upd({ name: e.target.value })} /><RetroInput label="SKU" value={f.sku ?? ''} onChange={(e) => upd({ sku: e.target.value.toUpperCase() })} /></Row>
          <Row><RetroSelect label="Categoría" value={f.categoryId ?? ''} onChange={(e) => upd({ categoryId: e.target.value })} options={[{ value: '', label: 'Sin categoría' }, ...(cats.data ?? []).map((c) => ({ value: c.id, label: `${c.icon ?? ''} ${c.name}` }))]} /><RetroSelect label="Tipo" value={f.kind} onChange={(e) => upd({ kind: e.target.value })} options={[{ value: 'SIMPLE', label: 'Producto' }, { value: 'COMBO', label: 'Combo' }]} /></Row>
          <RetroTextarea label="Descripción" value={f.description ?? ''} onChange={(e) => upd({ description: e.target.value })} />
          <Row><RetroInput label="Precio (con IVA)" inputMode="decimal" value={f.price ?? ''} onChange={(e) => upd({ price: e.target.value })} /><RetroSelect label="Impuesto" value={f.taxId ?? ''} onChange={(e) => upd({ taxId: e.target.value })} options={[{ value: '', label: 'Sin impuesto' }, ...(taxes.data ?? []).map((t) => ({ value: t.id, label: `${t.name} (${Math.round(t.rate * 100)}%)` }))]} /></Row>
          <Row><RetroSelect label="Estación de cocina" value={f.stationKey ?? ''} onChange={(e) => upd({ stationKey: e.target.value })} options={[{ value: '', label: 'Sin cocina (entrega directa)' }, ...STATION_KEYS.map((s) => ({ value: s, label: s }))]} /><RetroInput label="Tiempo de preparación (min)" type="number" value={f.prepMin ?? 5} onChange={(e) => upd({ prepMin: e.target.value })} /></Row>
          <Row><RetroInput label="Código de barras" value={f.barcode ?? ''} onChange={(e) => upd({ barcode: e.target.value })} /><RetroInput label="URL de imagen" value={f.imageUrl ?? ''} onChange={(e) => upd({ imageUrl: e.target.value })} /></Row>
          <div className="rb-row rb-wrap"><RetroCheck label="Disponible" checked={f.isAvailable ?? true} onChange={(e) => upd({ isAvailable: e.target.checked })} /><RetroCheck label="Inventariable (descarga receta)" checked={f.isInventoriable ?? true} onChange={(e) => upd({ isInventoriable: e.target.checked })} />{showCost && f.id && <span className="rb-end"><RetroBadge tone="dark">Costo {formatMoney2(f.cost)}</RetroBadge> <RetroBadge tone="ok">Margen {Math.round((f.margin ?? 0) * 100)}%</RetroBadge></span>}</div>
          <div className="rb-label">Variantes (tamaños)</div>
          {(f.variants ?? []).map((v: any, i: number) => <div key={i} className="rb-row"><RetroInput placeholder="Nombre" value={v.name} onChange={(e) => upd({ variants: f.variants.map((x: any, j: number) => (j === i ? { ...x, name: e.target.value } : x)) })} /><RetroInput placeholder="± precio" inputMode="decimal" value={v.priceDelta ?? 0} onChange={(e) => upd({ variants: f.variants.map((x: any, j: number) => (j === i ? { ...x, priceDelta: e.target.value } : x)) })} /><RetroInput placeholder="× receta" inputMode="decimal" value={v.qtyFactor ?? 1} onChange={(e) => upd({ variants: f.variants.map((x: any, j: number) => (j === i ? { ...x, qtyFactor: e.target.value } : x)) })} /><RetroButton size="sm" variant="ghost" onClick={() => upd({ variants: f.variants.filter((_: any, j: number) => j !== i) })}>✕</RetroButton></div>)}
          <RetroButton size="sm" variant="white" onClick={() => upd({ variants: [...(f.variants ?? []), { name: '', priceDelta: 0, qtyFactor: 1 }] })}>+ Variante</RetroButton>
          <div className="rb-label">Grupos de modificadores</div><div className="rb-row rb-wrap">{(groups.data ?? []).map((g) => <RetroCheck key={g.id} label={g.name} checked={(f.modifierGroupIds ?? []).includes(g.id)} onChange={(e) => upd({ modifierGroupIds: e.target.checked ? [...(f.modifierGroupIds ?? []), g.id] : f.modifierGroupIds.filter((x: string) => x !== g.id) })} />)}</div>
          {f.kind === 'COMBO' ? <>
            <div className="rb-label">Componentes del combo (con sustitutos permitidos)</div>
            {(f.comboSlots ?? []).map((s: any, i: number) => <div key={i} className="rb-card" style={{ boxShadow: 'none' }}><div className="rb-card__body rb-col" style={{ gap: 8 }}>
              <Row><RetroInput placeholder="Nombre del componente" value={s.name} onChange={(e) => upd({ comboSlots: f.comboSlots.map((x: any, j: number) => (j === i ? { ...x, name: e.target.value } : x)) })} /><RetroSelect value={s.defaultProductId} onChange={(e) => upd({ comboSlots: f.comboSlots.map((x: any, j: number) => (j === i ? { ...x, defaultProductId: e.target.value } : x)) })} options={[{ value: '', label: 'Producto por defecto…' }, ...simple.map((p) => ({ value: p.id, label: p.name }))]} /></Row>
              {(s.options ?? []).map((o: any, k: number) => <div key={k} className="rb-row"><RetroSelect value={o.productId} onChange={(e) => upd({ comboSlots: f.comboSlots.map((x: any, j: number) => (j === i ? { ...x, options: x.options.map((y: any, m: number) => (m === k ? { ...y, productId: e.target.value } : y)) } : x)) })} options={[{ value: '', label: 'Sustituto…' }, ...simple.map((p) => ({ value: p.id, label: p.name }))]} /><RetroInput placeholder="± precio" inputMode="decimal" value={o.priceDelta ?? 0} onChange={(e) => upd({ comboSlots: f.comboSlots.map((x: any, j: number) => (j === i ? { ...x, options: x.options.map((y: any, m: number) => (m === k ? { ...y, priceDelta: e.target.value } : y)) } : x)) })} /></div>)}
              <div className="rb-row"><RetroButton size="sm" variant="white" onClick={() => upd({ comboSlots: f.comboSlots.map((x: any, j: number) => (j === i ? { ...x, options: [...(x.options ?? []), { productId: '', priceDelta: 0 }] } : x)) })}>+ Sustituto</RetroButton><RetroButton size="sm" variant="ghost" onClick={() => upd({ comboSlots: f.comboSlots.filter((_: any, j: number) => j !== i) })}>Quitar componente</RetroButton></div></div></div>)}
            <RetroButton size="sm" variant="white" onClick={() => upd({ comboSlots: [...(f.comboSlots ?? []), { name: '', defaultProductId: '', options: [] }] })}>+ Componente</RetroButton></>
            : <><div className="rb-label">🧪 Receta (se descarga del inventario al vender)</div>
              {(f.recipe ?? []).map((r: any, i: number) => <div key={i} className="rb-row"><RetroSelect value={r.ingredientId} onChange={(e) => upd({ recipe: f.recipe.map((x: any, j: number) => (j === i ? { ...x, ingredientId: e.target.value } : x)) })} options={[{ value: '', label: 'Ingrediente…' }, ...(ings.data ?? []).map((g) => ({ value: g.id, label: `${g.name} (${g.unit})` }))]} /><RetroInput placeholder="Cantidad" inputMode="decimal" value={r.qty ?? ''} onChange={(e) => upd({ recipe: f.recipe.map((x: any, j: number) => (j === i ? { ...x, qty: e.target.value } : x)) })} /><RetroInput placeholder="Merma (0-0.99)" inputMode="decimal" value={r.wastePct ?? 0} onChange={(e) => upd({ recipe: f.recipe.map((x: any, j: number) => (j === i ? { ...x, wastePct: e.target.value } : x)) })} /><RetroButton size="sm" variant="ghost" onClick={() => upd({ recipe: f.recipe.filter((_: any, j: number) => j !== i) })}>✕</RetroButton></div>)}
              <RetroButton size="sm" variant="white" onClick={() => upd({ recipe: [...(f.recipe ?? []), { ingredientId: '', qty: '', wastePct: 0 }] })}>+ Ingrediente</RetroButton></>}
          {f.id && can('catalog.product.write') && <RetroButton variant="ink" size="sm" onClick={() => { if (confirm('¿Eliminar el producto? Las ventas históricas se conservan.')) remove.mutate(f.id); }}>🗑 Eliminar producto</RetroButton>}
        </>}
      </FormModal>
    </>
  );
}

function Categories() {
  const q = useGet<any[]>(['catalog', 'cats'], '/categories'); const [f, setF] = useState<any | null>(null);
  const save = useAct(() => { const b = { name: f.name, icon: f.icon || undefined, color: f.color || undefined, sortOrder: num(String(f.sortOrder ?? 0)), isActive: f.isActive ?? true }; return f.id ? put(`/categories/${f.id}`, b) : post('/categories', b); }, { invalidate: [['catalog'], ['menu']], ok: 'Categoría guardada', onSuccess: () => setF(null) });
  const remove = useAct((id: string) => del(`/categories/${id}`), { invalidate: [['catalog'], ['menu']], ok: 'Categoría eliminada', onSuccess: () => setF(null) });
  return <><div className="rb-row"><RetroButton variant="neon" onClick={() => setF({ name: '', icon: '🍔', sortOrder: 0, isActive: true })}>+ Categoría</RetroButton></div>
    <Async q={q}><RetroTable rows={q.data ?? []} onRowClick={setF} columns={[{ key: 'i', header: '', render: (r: any) => <span style={{ fontSize: '1.4rem' }}>{r.icon}</span> }, { key: 'name', header: 'Categoría' }, { key: 'o', header: 'Orden', numeric: true, render: (r: any) => r.sortOrder }, { key: 'a', header: 'Activa', render: (r: any) => (r.isActive ? '✅' : '⛔') }]} /></Async>
    <FormModal open={!!f} onClose={() => setF(null)} title="Categoría" size="sm" busy={save.isPending} disabled={!f?.name} onSubmit={() => save.mutate()}>{f && <><RetroInput label="Nombre" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /><Row><RetroInput label="Emoji" value={f.icon ?? ''} onChange={(e) => setF({ ...f, icon: e.target.value })} /><RetroInput label="Orden" type="number" value={f.sortOrder ?? 0} onChange={(e) => setF({ ...f, sortOrder: e.target.value })} /></Row><RetroCheck label="Activa" checked={f.isActive ?? true} onChange={(e) => setF({ ...f, isActive: e.target.checked })} />{f.id && <RetroButton size="sm" variant="ink" onClick={() => remove.mutate(f.id)}>Eliminar</RetroButton>}</>}</FormModal></>;
}

function Modifiers() {
  const q = useGet<any[]>(['catalog', 'groups'], '/modifier-groups'); const ings = useGet<any[]>(['ingredients'], '/ingredients'); const [f, setF] = useState<any | null>(null);
  const save = useAct(() => { const b = { name: f.name, type: f.type, minSelect: num(String(f.minSelect ?? 0)), maxSelect: num(String(f.maxSelect ?? 99)), modifiers: f.modifiers.filter((m: any) => m.name).map((m: any) => ({ name: m.name, priceDelta: num(String(m.priceDelta ?? 0)), ingredientId: m.ingredientId || null, qtyDelta: num(String(m.qtyDelta ?? 0)), isActive: m.isActive ?? true })) }; return f.id ? put(`/modifier-groups/${f.id}`, b) : post('/modifier-groups', b); }, { invalidate: [['catalog'], ['menu']], ok: 'Grupo guardado', onSuccess: () => setF(null) });
  return <><div className="rb-row"><RetroButton variant="neon" onClick={() => setF({ name: '', type: 'EXTRA', minSelect: 0, maxSelect: 5, modifiers: [{ name: '', priceDelta: 0, qtyDelta: 0 }] })}>+ Grupo</RetroButton></div>
    <Async q={q}><RetroTable rows={q.data ?? []} onRowClick={setF} columns={[{ key: 'name', header: 'Grupo' }, { key: 't', header: 'Tipo', render: (r: any) => <RetroBadge tone={r.type === 'REMOVE' ? 'danger' : 'ok'}>{r.type === 'EXTRA' ? '➕ Extras' : r.type === 'REMOVE' ? '🚫 Remover' : 'Opción'}</RetroBadge> }, { key: 'm', header: 'Opciones', render: (r: any) => r.modifiers.map((m: any) => m.name).join(', ') }]} /></Async>
    <FormModal open={!!f} onClose={() => setF(null)} title="Grupo de modificadores" size="lg" busy={save.isPending} disabled={!f?.name} onSubmit={() => save.mutate()}>{f && <>
      <Row><RetroInput label="Nombre" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /><RetroSelect label="Tipo" value={f.type} onChange={(e) => setF({ ...f, type: e.target.value })} options={[{ value: 'EXTRA', label: 'Extras (suman)' }, { value: 'REMOVE', label: 'Remover (restan)' }, { value: 'CHOICE', label: 'Opción única' }]} /></Row>
      <Row><RetroInput label="Mínimo a elegir" type="number" value={f.minSelect} onChange={(e) => setF({ ...f, minSelect: e.target.value })} /><RetroInput label="Máximo a elegir" type="number" value={f.maxSelect} onChange={(e) => setF({ ...f, maxSelect: e.target.value })} /></Row>
      <div className="rb-hint">Cada modificador puede afectar precio e inventario (cantidad + agrega consumo; − deja de consumir).</div>
      {f.modifiers.map((m: any, i: number) => <div key={i} className="rb-row rb-wrap"><RetroInput placeholder="Nombre" value={m.name} onChange={(e) => setF({ ...f, modifiers: f.modifiers.map((x: any, j: number) => (j === i ? { ...x, name: e.target.value } : x)) })} /><RetroInput placeholder="± precio" inputMode="decimal" value={m.priceDelta ?? 0} onChange={(e) => setF({ ...f, modifiers: f.modifiers.map((x: any, j: number) => (j === i ? { ...x, priceDelta: e.target.value } : x)) })} /><RetroSelect value={m.ingredientId ?? ''} onChange={(e) => setF({ ...f, modifiers: f.modifiers.map((x: any, j: number) => (j === i ? { ...x, ingredientId: e.target.value } : x)) })} options={[{ value: '', label: 'Sin inventario' }, ...(ings.data ?? []).map((g) => ({ value: g.id, label: g.name }))]} /><RetroInput placeholder="± cantidad" inputMode="decimal" value={m.qtyDelta ?? 0} onChange={(e) => setF({ ...f, modifiers: f.modifiers.map((x: any, j: number) => (j === i ? { ...x, qtyDelta: e.target.value } : x)) })} /><RetroButton size="sm" variant="ghost" onClick={() => setF({ ...f, modifiers: f.modifiers.filter((_: any, j: number) => j !== i) })}>✕</RetroButton></div>)}
      <RetroButton size="sm" variant="white" onClick={() => setF({ ...f, modifiers: [...f.modifiers, { name: '', priceDelta: 0, qtyDelta: 0 }] })}>+ Modificador</RetroButton></>}</FormModal></>;
}

function Ingredients() {
  const { can } = useSession(); const q = useGet<any[]>(['ingredients'], '/ingredients'); const [f, setF] = useState<any | null>(null);
  const save = useAct(() => { const b = { sku: f.sku, name: f.name, unit: f.unit, perishable: f.perishable ?? false, avgCost: num(String(f.avgCost ?? 0)), defaultMin: num(String(f.defaultMin ?? 0)), defaultMax: num(String(f.defaultMax ?? 0)) }; return f.id ? put(`/ingredients/${f.id}`, b) : post('/ingredients', b); }, { invalidate: [['ingredients']], ok: 'Ingrediente guardado', onSuccess: () => setF(null) });
  return <><div className="rb-row"><RetroButton variant="neon" onClick={() => setF({ sku: '', name: '', unit: 'g', perishable: false, avgCost: 0, defaultMin: 0, defaultMax: 0 })}>+ Ingrediente</RetroButton></div>
    <Async q={q}><RetroTable rows={q.data ?? []} onRowClick={setF} columns={[{ key: 'sku', header: 'SKU' }, { key: 'name', header: 'Ingrediente' }, { key: 'unit', header: 'Unidad' }, ...(can('catalog.cost.read') ? [{ key: 'c', header: 'Costo prom.', numeric: true, render: (r: any) => formatMoney2(r.avgCost) }] : []), { key: 'p', header: 'Perecedero', render: (r: any) => (r.perishable ? '❄️' : '') }]} /></Async>
    <FormModal open={!!f} onClose={() => setF(null)} title="Ingrediente" size="sm" busy={save.isPending} disabled={!f?.name || !f?.sku} onSubmit={() => save.mutate()}>{f && <><Row><RetroInput label="SKU" value={f.sku} onChange={(e) => setF({ ...f, sku: e.target.value.toUpperCase() })} /><RetroSelect label="Unidad" value={f.unit} onChange={(e) => setF({ ...f, unit: e.target.value })} options={UNITS.map((u) => ({ value: u, label: u }))} /></Row><RetroInput label="Nombre" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /><Row><RetroInput label="Costo por unidad" inputMode="decimal" value={f.avgCost ?? ''} onChange={(e) => setF({ ...f, avgCost: e.target.value })} /><RetroCheck label="Perecedero" checked={f.perishable ?? false} onChange={(e) => setF({ ...f, perishable: e.target.checked })} /></Row><Row><RetroInput label="Mínimo sugerido" inputMode="decimal" value={f.defaultMin ?? ''} onChange={(e) => setF({ ...f, defaultMin: e.target.value })} /><RetroInput label="Máximo sugerido" inputMode="decimal" value={f.defaultMax ?? ''} onChange={(e) => setF({ ...f, defaultMax: e.target.value })} /></Row></>}</FormModal></>;
}
