import { useState } from 'react';
import { RetroBadge, RetroButton, RetroCard, RetroInput, RetroSelect, RetroTable, RetroTabs, formatMoney2 } from '@retroburger/ui';
import { post } from '../app/api';
import { useAct, useGet } from '../app/hooks';
import { useSession } from '../app/auth';
import { Async, FormModal, NeedBranch, Row, fmtDate, num } from './common';

export default function Purchasing() { return <NeedBranch>{(b) => <Inner branchId={b} />}</NeedBranch>; }
const PO_TONE: Record<string, any> = { DRAFT: 'neutral', PENDING_APPROVAL: 'warn', SENT: 'info', PARTIAL: 'orange', RECEIVED: 'ok', CANCELLED: 'danger' };

function Inner({ branchId }: { branchId: string }) {
  const { can } = useSession(); const [tab, setTab] = useState<'orders' | 'suggest' | 'invoices'>('orders');
  const orders = useGet<any[]>(['purchasing', 'orders', branchId], '/purchase-orders', { branchId });
  const sugg = useGet<any[]>(['purchasing', 'sugg', branchId], '/purchase-suggestions', { branchId }, { enabled: tab === 'suggest' });
  const invoices = useGet<any[]>(['purchasing', 'inv'], '/supplier-invoices', {}, { enabled: tab === 'invoices' });
  const suppliers = useGet<any[]>(['suppliers'], '/suppliers'); const ingredients = useGet<any[]>(['ingredients'], '/ingredients');
  const [po, setPo] = useState<any | null>(null); const [detail, setDetail] = useState<any | null>(null); const [recv, setRecv] = useState<Record<string, string>>({});
  const [inv, setInv] = useState<any | null>(null);
  const keys = [['purchasing'], ['inventory']];
  const create = useAct(() => post('/purchase-orders', { branchId, supplierId: po.supplierId, items: po.items.filter((i: any) => i.ingredientId && num(i.qty) > 0).map((i: any) => ({ ingredientId: i.ingredientId, qty: num(i.qty), unitPrice: num(i.unitPrice) })) }), { invalidate: keys, ok: 'Orden creada', onSuccess: () => setPo(null) });
  const step = useAct((v: { id: string; a: string }) => post(`/purchase-orders/${v.id}/${v.a}`), { invalidate: keys, ok: 'Orden actualizada', onSuccess: (r) => setDetail(r) });
  const receive = useAct(() => post(`/purchase-orders/${detail.id}/receive`, { items: Object.entries(recv).filter(([, v]) => num(v) > 0).map(([ingredientId, v]) => ({ ingredientId, qty: num(v) })) }), { invalidate: keys, ok: '📦 Mercancía recibida', onSuccess: (r) => { setDetail(r); setRecv({}); } });
  const createInv = useAct(() => post('/supplier-invoices', { supplierId: inv.supplierId, purchaseOrderId: inv.purchaseOrderId || undefined, invoiceNumber: inv.invoiceNumber, total: num(inv.total) }), { invalidate: keys, ok: 'Factura registrada', onSuccess: () => setInv(null) });
  const pay = useAct((id: string) => post(`/supplier-invoices/${id}/pay`), { invalidate: keys, ok: 'Factura pagada' });
  const fromSugg = (s: any) => setPo({ supplierId: s.bestSupplier?.supplierId ?? '', items: [{ ingredientId: s.ingredientId, qty: String(Math.ceil(s.suggestedQty)), unitPrice: String(s.bestSupplier?.price ?? '') }] });
  const poTotal = (po?.items ?? []).reduce((a: number, i: any) => a + num(i.qty ?? '0') * num(i.unitPrice ?? '0'), 0);
  const open = async (id: string) => { const { get } = await import('../app/api'); setDetail(await get(`/purchase-orders/${id}`)); setRecv({}); };

  return (
    <>
      <RetroTabs value={tab} onChange={setTab} tabs={[{ key: 'orders', label: '🛒 Órdenes de compra' }, { key: 'suggest', label: '💡 Sugerencias' }, { key: 'invoices', label: '🧾 Facturas de proveedor' }]} />
      {tab === 'orders' && <><div className="rb-row">{can('purchasing.order.write', branchId) && <RetroButton variant="neon" onClick={() => setPo({ supplierId: '', items: [{ ingredientId: '', qty: '', unitPrice: '' }] })}>+ Nueva orden de compra</RetroButton>}</div>
        <Async q={orders}><RetroTable rows={orders.data ?? []} onRowClick={(r) => void open(r.id)} columns={[{ key: 'n', header: 'OC', render: (r: any) => `#${r.number}` }, { key: 's', header: 'Proveedor', render: (r: any) => r.supplier }, { key: 'st', header: 'Estado', render: (r: any) => <RetroBadge tone={PO_TONE[r.status]}>{r.status}</RetroBadge> }, { key: 'at', header: 'Fecha', render: (r: any) => fmtDate(r.createdAt) }, { key: 't', header: 'Total', numeric: true, render: (r: any) => formatMoney2(r.total) }]} /></Async></>}
      {tab === 'suggest' && <Async q={sugg}><RetroTable rows={sugg.data ?? []} rowKey={(r) => r.ingredientId} columns={[{ key: 'n', header: 'Insumo', render: (r: any) => r.name }, { key: 'q', header: 'Existencia', numeric: true, render: (r: any) => `${r.qty} ${r.unit}` }, { key: 'm', header: 'Mínimo', numeric: true, render: (r: any) => r.minQty }, { key: 's', header: 'Sugerido', numeric: true, render: (r: any) => Math.ceil(r.suggestedQty) }, { key: 'p', header: 'Mejor proveedor', render: (r: any) => (r.bestSupplier ? `${r.bestSupplier.supplier} · ${formatMoney2(r.bestSupplier.price)}` : '—') }, { key: 'a', header: '', render: (r: any) => can('purchasing.order.write', branchId) && <RetroButton size="sm" variant="mustard" onClick={() => fromSugg(r)}>Ordenar</RetroButton> }]} empty="Todo el inventario está sobre su mínimo ✅" /></Async>}
      {tab === 'invoices' && <><div className="rb-row"><RetroButton variant="neon" onClick={() => setInv({ supplierId: '', purchaseOrderId: '', invoiceNumber: '', total: '' })}>+ Registrar factura</RetroButton></div><Async q={invoices}><RetroTable rows={invoices.data ?? []} columns={[{ key: 's', header: 'Proveedor', render: (r: any) => r.supplier }, { key: 'n', header: 'Factura', render: (r: any) => r.invoiceNumber }, { key: 't', header: 'Total', numeric: true, render: (r: any) => formatMoney2(r.total) }, { key: 'f', header: 'Alertas', render: (r: any) => r.priceVarianceFlag && <RetroBadge tone="warn">⚠️ Difiere de lo recibido</RetroBadge> }, { key: 'st', header: 'Estado', render: (r: any) => r.status }, { key: 'a', header: '', render: (r: any) => r.status === 'PENDING' && can('purchasing.order.approve') && <RetroButton size="sm" variant="neon" onClick={() => pay.mutate(r.id)}>Pagar</RetroButton> }]} /></Async></>}

      <FormModal open={!!po} onClose={() => setPo(null)} title="Nueva orden de compra" size="lg" busy={create.isPending} disabled={!po?.supplierId || poTotal <= 0} onSubmit={() => create.mutate()}>
        {po && <><RetroSelect label="Proveedor" value={po.supplierId} onChange={(e) => setPo({ ...po, supplierId: e.target.value })} options={[{ value: '', label: 'Selecciona…' }, ...(suppliers.data ?? []).filter((s) => s.isActive).map((s) => ({ value: s.id, label: s.name }))]} />
          {po.items.map((it: any, i: number) => <Row key={i}><RetroSelect label={i === 0 ? 'Insumo' : undefined} value={it.ingredientId} onChange={(e) => { const sp = suppliers.data?.find((s) => s.id === po.supplierId)?.products.find((p: any) => p.ingredientId === e.target.value); setPo({ ...po, items: po.items.map((x: any, j: number) => (j === i ? { ...x, ingredientId: e.target.value, unitPrice: x.unitPrice || String(sp?.price ?? '') } : x)) }); }} options={[{ value: '', label: 'Selecciona…' }, ...(ingredients.data ?? []).map((g) => ({ value: g.id, label: `${g.name} (${g.unit})` }))]} />
            <div className="rb-row"><RetroInput label={i === 0 ? 'Cantidad' : undefined} inputMode="decimal" value={it.qty} onChange={(e) => setPo({ ...po, items: po.items.map((x: any, j: number) => (j === i ? { ...x, qty: e.target.value } : x)) })} /><RetroInput label={i === 0 ? 'Precio unit.' : undefined} inputMode="decimal" value={it.unitPrice} onChange={(e) => setPo({ ...po, items: po.items.map((x: any, j: number) => (j === i ? { ...x, unitPrice: e.target.value } : x)) })} /></div></Row>)}
          <RetroButton size="sm" variant="white" onClick={() => setPo({ ...po, items: [...po.items, { ingredientId: '', qty: '', unitPrice: '' }] })}>+ Agregar renglón</RetroButton><div className="rb-display" style={{ fontSize: '1.4rem' }}>Total: {formatMoney2(poTotal)}</div></>}
      </FormModal>
      <FormModal open={!!detail} onClose={() => setDetail(null)} title={detail ? `OC #${detail.number} · ${detail.supplier}` : ''} size="lg" onSubmit={() => (['SENT', 'PARTIAL'].includes(detail?.status) ? receive.mutate() : setDetail(null))} submitLabel={['SENT', 'PARTIAL'].includes(detail?.status) ? 'Recibir mercancía' : 'Cerrar'} busy={receive.isPending}>
        {detail && <><div className="rb-row"><RetroBadge tone={PO_TONE[detail.status]}>{detail.status}</RetroBadge><span className="rb-end rb-display">{formatMoney2(detail.total)}</span></div>
          <RetroTable rows={detail.items} rowKey={(i: any) => i.ingredientId} columns={[{ key: 'n', header: 'Insumo', render: (i: any) => i.name }, { key: 'q', header: 'Ordenado', numeric: true, render: (i: any) => `${i.qty} ${i.unit}` }, { key: 'r', header: 'Recibido', numeric: true, render: (i: any) => i.qtyReceived }, { key: 'p', header: 'Precio', numeric: true, render: (i: any) => formatMoney2(i.unitPrice) },
            ...(['SENT', 'PARTIAL'].includes(detail.status) ? [{ key: 'x', header: 'Recibir ahora', render: (i: any) => <input className="rb-input" style={{ maxWidth: 110 }} inputMode="decimal" value={recv[i.ingredientId] ?? ''} placeholder={String(Math.max(i.qty - i.qtyReceived, 0))} onChange={(e) => setRecv({ ...recv, [i.ingredientId]: e.target.value })} /> }] : [])]} />
          <div className="rb-row rb-wrap">{detail.status === 'DRAFT' && <RetroButton variant="mustard" onClick={() => step.mutate({ id: detail.id, a: 'submit' })}>Enviar al proveedor</RetroButton>}{detail.status === 'PENDING_APPROVAL' && can('purchasing.order.approve') && <RetroButton variant="neon" onClick={() => step.mutate({ id: detail.id, a: 'approve' })}>Aprobar</RetroButton>}{['DRAFT', 'PENDING_APPROVAL', 'SENT'].includes(detail.status) && <RetroButton variant="ghost" onClick={() => step.mutate({ id: detail.id, a: 'cancel' })}>Cancelar orden</RetroButton>}</div></>}
      </FormModal>
      <FormModal open={!!inv} onClose={() => setInv(null)} title="Factura de proveedor" size="sm" busy={createInv.isPending} disabled={!inv?.supplierId || !inv?.invoiceNumber || !num(inv?.total ?? '0')} onSubmit={() => createInv.mutate()}>
        {inv && <><RetroSelect label="Proveedor" value={inv.supplierId} onChange={(e) => setInv({ ...inv, supplierId: e.target.value })} options={[{ value: '', label: 'Selecciona…' }, ...(suppliers.data ?? []).map((s) => ({ value: s.id, label: s.name }))]} /><RetroSelect label="Orden de compra (cotejo)" value={inv.purchaseOrderId} onChange={(e) => setInv({ ...inv, purchaseOrderId: e.target.value })} options={[{ value: '', label: 'Sin orden' }, ...(orders.data ?? []).filter((o) => o.supplier === suppliers.data?.find((s) => s.id === inv.supplierId)?.name).map((o) => ({ value: o.id, label: `OC #${o.number} · ${formatMoney2(o.total)}` }))]} /><RetroInput label="Folio" value={inv.invoiceNumber} onChange={(e) => setInv({ ...inv, invoiceNumber: e.target.value })} /><RetroInput label="Total" inputMode="decimal" value={inv.total} onChange={(e) => setInv({ ...inv, total: e.target.value })} /></>}
      </FormModal>
      <RetroCard title="" tone="plain"><span className="rb-hint">Las órdenes que superan el umbral configurado requieren aprobación de un gerente. Cada recepción actualiza kardex, lotes y costo promedio.</span></RetroCard>
    </>
  );
}
